# Serverless definition file
# --------------------------
# Defines Lambda functions to be deployed to AWS using the Serverless Framework.
# http://serverless.com
#
# This creates an API which proxies to lambda

service: example-weather-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  memorySize: 128
  timeout: 10
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
